# path
export ZSH_D=$HOME/.zsh.d

# Set prompt
export rca_shell_prompt_mode=normal

# Common
source "$ZSH_D/bootstrap.zsh"
source "$ZSH_D/configs.zsh"
source "$ZSH_D/prompt/index.zsh"
source "$ZSH_D/alias/alias_common.zsh"

# OS/Arch specific
source "$ZSH_D/alias/alias_macos.zsh"
source "$ZSH_D/common/macos.zsh"

# Created by newuser for 5.9
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# Perl
PERL_MM_OPT="INSTALL_BASE=$HOME/perl5"
# eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

